name: Coverage

on: [pull_request, push]

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust
        run: rustup update stable
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage (Rust)
        run: cargo llvm-cov -p evaluatio-core --release --codecov --output-path coverage_rust.json
      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Generate code coverage (Python)
        run: uv run -m pytest && uv run coverage json -o "coverage_python.json" --omit "python-tests/**"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required for private repos or protected branches
          files: coverage_rust.json coverage_python.json
          fail_ci_if_error: true